#!/usr/bin/python3
# -*- coding: utf-8; tab-width: 4; indent-tabs-mode: t -*-

import glob

for fn in glob.glob("*.ebuild"):
    with open(fn, "a") as f:
        f.write("""
pkg_extra_files() {
        # based on FreeDesktop shared-mime-info Specification (https://specifications.freedesktop.org/shared-mime-info-spec/shared-mime-info-spec-0.21.html)
        # the following files are generated by "/usr/bin/update-mime-database", except "/usr/share/mime/packages"
        echo "/usr/share/mime/aliases"
        echo "/usr/share/mime/application/***"
        echo "/usr/share/mime/audio/***"
        echo "/usr/share/mime/font/***"
        echo "/usr/share/mime/generic-icons"
        echo "/usr/share/mime/globs"
        echo "/usr/share/mime/globs2"
        echo "/usr/share/mime/icons"
        echo "/usr/share/mime/image/***"
        echo "/usr/share/mime/inode/***"
        echo "/usr/share/mime/magic"
        echo "/usr/share/mime/message/***"
        echo "/usr/share/mime/mime.cache"
        echo "/usr/share/mime/model/***"
        echo "/usr/share/mime/multipart/***"
        echo "/usr/share/mime/subclasses"
        echo "/usr/share/mime/text/***"
        echo "/usr/share/mime/treemagic"
        echo "/usr/share/mime/types"
        echo "/usr/share/mime/version"
        echo "/usr/share/mime/video/***"
        echo "/usr/share/mime/x-content/***"
        echo "/usr/share/mime/x-epoc/***"
        echo "/usr/share/mime/XMLnamespaces"
}
""")
