#!/usr/bin/python3
# -*- coding: utf-8; tab-width: 4; indent-tabs-mode: t -*-

import glob

for fn in glob.glob("*.ebuild"):
    with open(fn, "a") as f:
        f.write("""
pkg_extra_files() {
        # this file is generated by /etc/dconf/db/ibus.d/*
        echo "/etc/dconf/db/ibus"

        echo "~/.config/ibus"
        echo "~/.config/ibus/bus/***"
        echo "~/.cache/ibus"
        echo "~/.cache/ibus/bus/***"
}
""")
